### ISSUE TITLE
Status bar reappears after selecting a picture from gallery

### ISSUE THREAD

**Issue by steodor** [katzer/cordova-plugin-hidden-statusbar-overlay#1]
Hi, nice plugin!

However, when selecting a file using the `org.apache.cordova.camera` plugin with the following options:

```
destinationType: navigator.camera.DestinationType.FILE_URI,
sourceType: navigator.camera.PictureSourceType.SAVEDPHOTOALBUM,
```

...the status bar appears (before actually selecting a file, not after, so just as the file selection widget pops up) and doesn't go away after a file has been chosen, remaining on top of my app afterwards.

Is there any way you can fix this? I assume you need to track intents and re-hide the status bar after each intent has finished. Please let me know when you get a chance to look into it.

Thank you

**Comment by abishkjswl13** [comment]
StatusBar.hide();
StatusBar.show();
$("#page_id").css("position","fixed");
