### ISSUE TITLE
Cannot get the plugin to work

### ISSUE THREAD

**Issue by erol-simsir-fe** [katzer/cordova-plugin-hidden-statusbar-overlay#3]
I've forked the plugin directly into the plugins folder of my project. I've included "<gap:plugin name="de.appplant.cordova.plugin.hidden-statusbar-overlay" />" into the config.xml file and I've added the JS to hide the statusbar when it appears (because it has to be hidden when this plugin is installed) to my index.html. The statusbar doesn't disappear though.

So what I'm wondering is if this plugin also works with the PhoneGap Developer App (http://app.phonegap.com/). I haven't tested this by installing the app on my device, because I don't have an Apple Developer account.

- So, have I installed the plugin incorrectly?
- And/Or does this not work because the PhoneGap Developer App doesn't support 3rd party plugins?

**Comment by katzer** [comment]
You need to install the plugin via CLI.
